// ============================================================
// HOW TO ADD A NEW TOOL:
// Copy one block below, paste at the end of the array,
// fill in the details, save, and re-upload to GitHub.
// ============================================================

const TOOLS = [
  {name:'ChatGPT',cat:'chatbot',icon:'🤖',color:'#10a37f',pricing:'Freemium',pricingDetail:'Free / $20mo',rating:4.8,reviews:'2.4M',url:'https://chat.openai.com',desc:'OpenAI\'s flagship AI assistant. Best for general tasks, coding, writing, research, and voice conversations.',pros:['Most capable general model','Huge plugin/GPT ecosystem','Excellent voice mode','Strong reasoning (o1 model)'],cons:['Can hallucinate facts','Rate limits on free tier','No real-time search on free']},
  {name:'Claude',cat:'chatbot',icon:'✦',color:'#cc785c',pricing:'Freemium',pricingDetail:'Free / $20mo',rating:4.7,reviews:'820K',url:'https://claude.ai',desc:'Anthropic\'s AI assistant. Exceptional for long documents, nuanced writing, coding, and safety-conscious tasks.',pros:['Best-in-class writing quality','Huge 200K context window','Thoughtful & nuanced replies','Strong at reasoning & analysis'],cons:['No image generation','Fewer integrations than GPT','Token limits on free tier']},
  {name:'Gemini',cat:'chatbot',icon:'♊',color:'#4285f4',pricing:'Freemium',pricingDetail:'Free / $20mo',rating:4.5,reviews:'1.1M',url:'https://gemini.google.com',desc:'Google\'s multimodal AI with deep integration into Google Workspace — Gmail, Docs, Drive, and more.',pros:['Native Google ecosystem integration','Excellent multimodal understanding','Real-time web search','350M monthly users'],cons:['Can be verbose','Lags GPT-4 on complex reasoning','Privacy concerns for some']},
  {name:'Perplexity AI',cat:'research',icon:'🔍',color:'#20b2aa',pricing:'Freemium',pricingDetail:'Free / $20mo',rating:4.6,reviews:'430K',url:'https://perplexity.ai',desc:'AI-powered search engine that gives cited, sourced answers in real time. Replacing Google for many users.',pros:['Real-time web search with citations','Clean, fast interface','Great for research tasks','Accurate source attribution'],cons:['Less conversational than GPT','Free tier has daily limits','Can miss nuance in complex topics']},
  {name:'Microsoft Copilot',cat:'productivity',icon:'🪟',color:'#0078d4',pricing:'Freemium',pricingDetail:'Free / $30mo',rating:4.4,reviews:'890K',url:'https://copilot.microsoft.com',desc:'AI assistant deeply embedded in Microsoft 365 — Word, Excel, PowerPoint, Outlook, and Teams.',pros:['Native Office 365 integration','Real-time web access','Free on Windows','Enterprise-ready'],cons:['Best features need M365 subscription','Less capable than GPT-4 standalone','Inconsistent in complex tasks']},
  {name:'Jasper AI',cat:'writing',icon:'✍️',color:'#ff5c35',pricing:'Paid',pricingDetail:'From $39/mo',rating:4.4,reviews:'340K',url:'https://jasper.ai',desc:'Enterprise-grade AI writing platform for marketing teams. Generates long-form blogs, ad copy, and brand-consistent content.',pros:['100+ content templates','Brand voice training','Multi-language support (25+)','Team collaboration features'],cons:['Expensive for solo users','Outputs need human editing','Built on same models as competitors']},
  {name:'Copy.ai',cat:'writing',icon:'📝',color:'#6c63ff',pricing:'Freemium',pricingDetail:'Free / $36mo',rating:4.3,reviews:'210K',url:'https://copy.ai',desc:'Fast AI copy generator focused on marketing: ads, emails, product descriptions, and social media posts.',pros:['90+ content templates','Fast output generation','Good free tier','Sales-focused workflows'],cons:['Content can feel generic','Not ideal for long-form','Fewer brand customization options']},
  {name:'Grammarly',cat:'writing',icon:'📖',color:'#15c39a',pricing:'Freemium',pricingDetail:'Free / $12mo',rating:4.7,reviews:'1.8M',url:'https://grammarly.com',desc:'AI writing assistant for grammar, tone, clarity, and style. Works everywhere in your browser.',pros:['Works across all platforms','Excellent grammar correction','Tone & clarity suggestions','Plagiarism checker on Premium'],cons:['AI suggestions can be over-aggressive','Premium cost adds up','Not ideal for creative writing']},
  {name:'Writesonic',cat:'writing',icon:'⚡',color:'#7c3aed',pricing:'Freemium',pricingDetail:'Free / $16mo',rating:4.3,reviews:'180K',url:'https://writesonic.com',desc:'AI writer with SEO focus — includes Chatsonic (ChatGPT with real-time search) and bulk content generation.',pros:['Built-in real-time search','SEO-optimized outputs','Affordable pricing','Bulk generation capabilities'],cons:['Quality varies by template','UI can feel cluttered','Inconsistent on technical topics']},
  {name:'Midjourney',cat:'image',icon:'🎨',color:'#9b59b6',pricing:'Paid',pricingDetail:'From $10/mo',rating:4.8,reviews:'950K',url:'https://midjourney.com',desc:'Industry-leading AI image generator known for stunning artistic quality. Used by professionals worldwide.',pros:['Best artistic quality overall','Highly stylized outputs','Active community','Regular model updates'],cons:['Discord-only interface','No free tier','Steep learning curve for prompts']},
  {name:'DALL·E 3',cat:'image',icon:'🖼️',color:'#10a37f',pricing:'Freemium',pricingDetail:'Via ChatGPT Plus',rating:4.5,reviews:'620K',url:'https://openai.com/dall-e-3',desc:'OpenAI\'s image model integrated in ChatGPT. Excellent at following detailed text prompts accurately.',pros:['Excellent prompt adherence','Integrated with ChatGPT','Handles text in images well','Easy to use'],cons:['Less artistic than Midjourney','Limited fine-grained control','Slower than some alternatives']},
  {name:'Stable Diffusion',cat:'image',icon:'🌊',color:'#e67e22',pricing:'Free',pricingDetail:'Open source',rating:4.4,reviews:'480K',url:'https://stability.ai',desc:'Open-source image generation model. Run it locally or via API. Full control, no restrictions.',pros:['Completely free & open source','Run locally for full privacy','Highly customizable','Massive model ecosystem'],cons:['Requires technical setup','Hardware requirements for local','Steep learning curve']},
  {name:'Adobe Firefly',cat:'image',icon:'🔥',color:'#e74c3c',pricing:'Freemium',pricingDetail:'Free / $5mo',rating:4.5,reviews:'390K',url:'https://firefly.adobe.com',desc:'Adobe\'s AI image tools trained on licensed content — safe for commercial use and integrated with Creative Cloud.',pros:['Commercially safe IP','Integrated with Photoshop/Illustrator','Generative fill feature','High-quality outputs'],cons:['Creative Cloud lock-in','Less experimental than Midjourney','Slower iteration speed']},
  {name:'Canva AI',cat:'image',icon:'🟣',color:'#7c3aed',pricing:'Freemium',pricingDetail:'Free / $15mo',rating:4.6,reviews:'1.2M',url:'https://canva.com',desc:'Design platform with powerful AI features: Magic Studio, text-to-image, background removal, and auto-resize.',pros:['Beginner-friendly','All-in-one design platform','Great templates library','Strong AI Magic suite'],cons:['Less control than pro tools','Premium features add up','Output can look templated']},
  {name:'GitHub Copilot',cat:'coding',icon:'🐙',color:'#6e5494',pricing:'Paid',pricingDetail:'$10/mo or $100/yr',rating:4.7,reviews:'760K',url:'https://github.com/features/copilot',desc:'AI pair programmer integrated into VS Code, JetBrains, and more. Suggests code, docstrings, and tests in real time.',pros:['Deep IDE integration','Excellent code completion','Supports all major languages','Learns from your codebase'],cons:['Can suggest outdated patterns','$10/mo cost','May reproduce licensed code']},
  {name:'Cursor',cat:'coding',icon:'⌨️',color:'#6c63ff',pricing:'Freemium',pricingDetail:'Free / $20mo',rating:4.8,reviews:'290K',url:'https://cursor.so',desc:'AI-first code editor (VS Code fork). Chat with your codebase, generate entire files, and fix bugs conversationally.',pros:['Best AI coding experience','Chat with full codebase','Generates multi-file changes','Fast & responsive'],cons:['New — can have bugs','Paid for full features','Learning curve from VS Code']},
  {name:'Replit AI',cat:'coding',icon:'🔄',color:'#f26207',pricing:'Freemium',pricingDetail:'Free / $25mo',rating:4.3,reviews:'340K',url:'https://replit.com',desc:'Browser-based IDE with AI that can build and deploy full apps. Great for beginners and rapid prototyping.',pros:['No setup needed','Deploy instantly','AI builds full apps','Great for beginners'],cons:['Slower than local editors','Free tier is limited','Performance varies']},
  {name:'HeyGen',cat:'video',icon:'🎬',color:'#ff4d6d',pricing:'Freemium',pricingDetail:'Free / $24mo',rating:4.5,reviews:'180K',url:'https://heygen.com',desc:'AI avatar video creation platform. Create realistic talking-head videos with custom avatars and voice cloning.',pros:['Realistic AI avatars','Voice cloning','Multi-language support','Fast rendering'],cons:['Expensive at scale','Avatar quality varies','Limited free tier']},
  {name:'Runway',cat:'video',icon:'🛤️',color:'#00c4cc',pricing:'Freemium',pricingDetail:'Free / $12mo',rating:4.5,reviews:'220K',url:'https://runwayml.com',desc:'Professional AI video generation and editing. Gen-2 model creates clips from text or images. Used by filmmakers.',pros:['Professional-grade quality','Text/image to video','Advanced editing tools','Growing model library'],cons:['Expensive for heavy use','Short clip length limits','Needs good prompting']},
  {name:'ElevenLabs',cat:'video',icon:'🎙️',color:'#2563eb',pricing:'Freemium',pricingDetail:'Free / $5mo',rating:4.7,reviews:'290K',url:'https://elevenlabs.io',desc:'Best-in-class AI voice synthesis and cloning. Produces incredibly realistic speech from text in 29+ languages.',pros:['Ultra-realistic voice quality','Voice cloning in seconds','29+ languages','Mobile app available'],cons:['Free tier limited credits','Voice cloning ethical concerns','Best voices are paywalled']},
  {name:'Notion AI',cat:'productivity',icon:'🗒️',color:'#191919',pricing:'Paid',pricingDetail:'$10/mo add-on',rating:4.5,reviews:'520K',url:'https://notion.so/product/ai',desc:'AI writing and summarization built into Notion. Draft, edit, summarize, and auto-organize your workspace.',pros:['Integrated into your workspace','Excellent summarization','Template generation','Q&A over your docs'],cons:['Add-on cost on top of Notion','Not a standalone tool','Limited compared to dedicated AI']},
  {name:'Zapier AI',cat:'productivity',icon:'⚡',color:'#ff4a00',pricing:'Freemium',pricingDetail:'Free / $20mo',rating:4.4,reviews:'380K',url:'https://zapier.com/ai',desc:'AI-powered automation platform connecting 8,000+ apps. Build workflows and agents that work without you.',pros:['8000+ app integrations','No-code automation','AI workflow builder','Huge time saver'],cons:['Expensive at scale','Complex for beginners','AI agent features are new']},
  {name:'Otter.ai',cat:'productivity',icon:'🦦',color:'#00b4d8',pricing:'Freemium',pricingDetail:'Free / $10mo',rating:4.4,reviews:'290K',url:'https://otter.ai',desc:'AI meeting assistant that transcribes, summarizes, and generates action items from your meetings in real time.',pros:['Real-time transcription','Auto action items','Integrates with Zoom/Meet','Searchable transcripts'],cons:['Accuracy drops with accents','Free limit (300min/mo)','Bot joins your meetings']},
  {name:'Surfer SEO',cat:'seo',icon:'🏄',color:'#00a896',pricing:'Paid',pricingDetail:'From $79/mo',rating:4.5,reviews:'120K',url:'https://surferseo.com',desc:'AI-powered SEO content optimization platform. Score your content, find keywords, and rank higher on Google.',pros:['Real-time content scoring','Keyword research built in','Content editor with AI','Competitor analysis'],cons:['Expensive','Steep learning curve','Focused on English content']},
];

// ============================================================
// HOW TO ADD A NEW SAAS PRODUCT:
// Copy one block, fill in your real product details, save & upload
// ============================================================
const SAAS_PRODUCTS = [
  {icon:'🚀',color:'rgba(232,255,90,0.1)',name:'Product One',desc:'Your first SaaS product is in development. Update this with the real name and description.',features:['Feature one — describe what it does','Feature two — key benefit','Feature three — unique selling point']},
  {icon:'⚡',color:'rgba(79,156,249,0.1)',name:'Product Two',desc:'Another powerful SaaS tool coming soon. Describe the problem it solves here.',features:['Feature one placeholder','Feature two placeholder','Feature three placeholder']},
  {icon:'🛠️',color:'rgba(167,139,250,0.1)',name:'Product Three',desc:'Third SaaS product in the pipeline. Update with your actual product details.',features:['Feature one placeholder','Feature two placeholder','Feature three placeholder']},
];

// ============================================================
// HOW TO ADD A NEW BLOG POST:
// 1. Add entry below with slug matching a file in /blog/ folder
// 2. Create the matching blog/your-slug.html file
// 3. Save both files and upload to GitHub
// ============================================================
const BLOGS = [
  {slug:'chatgpt-vs-claude-vs-gemini',tag:'Comparison',title:'ChatGPT vs Claude vs Gemini: Which AI Is Best in 2026?',excerpt:'We tested all three flagship models across 50+ tasks. Here\'s what we found — and which one you should actually pay for.',date:'Mar 28, 2026',readTime:'8 min read'},
  {slug:'best-free-ai-tools',tag:'Guide',title:'The Best Free AI Tools You Can Use Right Now (No Credit Card)',excerpt:'A curated list of genuinely useful AI tools that won\'t cost you a dollar. Tested and ranked by real utility.',date:'Mar 27, 2026',readTime:'6 min read'},
  {slug:'ai-coding-tools-replacing-developers',tag:'Deep Dive',title:'Why AI Coding Tools Are Replacing Junior Developers',excerpt:'Cursor, Copilot, and Claude Code are changing who gets hired. Here\'s an honest look at what this means for developers.',date:'Mar 26, 2026',readTime:'10 min read'},
  {slug:'top-ai-tools-march-2026',tag:'News',title:'Top 10 AI Tools That Launched This Month — March 2026',excerpt:'A roundup of the newest, most exciting AI tools that dropped this month — with quick verdicts on each.',date:'Mar 25, 2026',readTime:'5 min read'},
  {slug:'personal-ai-workflow',tag:'Tutorial',title:'How To Build a Personal AI Workflow in Under 30 Minutes',excerpt:'Stop juggling 10 tabs. Here\'s how to set up a lean, powerful AI workflow using just 3 tools.',date:'Mar 24, 2026',readTime:'7 min read'},
  {slug:'ai-tools-that-actually-work',tag:'Opinion',title:'The AI Hype Cycle Is Real — But These 5 Tools Actually Deliver',excerpt:'Most AI tools disappoint. But after testing hundreds of them, these five have genuinely changed how I work.',date:'Mar 23, 2026',readTime:'9 min read'},
];
